### PR TITLE
Implement InputMap#ifConsumed

### PR DESCRIPTION
**Pull request by JordanMartinez**

### CODE REVIEW

**Comment by TomasMikula** [comment]
Thanks! 👍

**Comment by JordanMartinez** [comment]
Can you make a new snapshot release? Then I can finish the sanity checking for RichTextFX.

**Comment by TomasMikula** [comment]
Done.

For some reason, one test fails on my OS X,

    org.fxmisc.wellbehaved.event.EventMatchingTest:60

This doesn't seem related to your recent PRs, neither does it fail on the Travis build. It is probably some inconsistency in JavaFX in how events are handled on different OSes and I never ran the tests on OS X before...

**Comment by TomasMikula** [comment]
Oh, my memory is short. I did test it on OS X before and even reported it: [JDK-8134723](https://bugs.openjdk.java.net/browse/JDK-8134723).

**Comment by JordanMartinez** [comment]
Lol... Still, why has no one done anything on that bug? Is it really that hard to fix? Or is it just lack of time/priority?

Ok, I'll get to work on it.

**Comment by TomasMikula** [comment]
I would say it's lack of priority, but I have no idea how ugly it can become underneath.

**Pull request merged**
