### PR TITLE
Post process

### PR DESCRIPTION
**Pull request by JordanMartinez**
The first commit is a duplicate of my other PR's first commit. It shouldn't matter since you'll merge both once everything's fixed up.

### CODE REVIEW

**Comment by TomasMikula** [comment]
Looks good. I don't know whether `postProcess` is a good name. Perhaps `ifConsumed` is in the end better? Something else?

**Comment by TomasMikula** [comment]
It would also be more useful as non-static.

**Comment by JordanMartinez** [comment]
> erhaps ifConsumed is in the end better?

I only copied the name of the test. Since the process only runs when the event is consumed, it should be `ifConsumed`. It also matches the name of how things worked in the non-experimental package, so people will probably have an easier time upgrading to that anyways... 

> It would also be more useful as non-static.

Oh right :-)

**Comment by JordanMartinez** [comment]
How do I reference the original InputMapTemplate? 

I could write the following, but I feel like there is a better way I don't know of:
````java
InputMapTemplate<S, T> thisObj = this;
@Override protected InputHandlerTemplateMap<S, T> getInputHandlerTemplateMap() {
    return thisObj.getInputHandlerTemplateMap().map(iht -> { /* code... */ }
}
````

**Comment by TomasMikula** [comment]
You can reference it using

```java
InputMapTemplate.this
```

**Comment by JordanMartinez** [comment]
I thought I already tried that and it didn't work. Tried it again and it did. Must have been something else at the time...

K. I'll force-push this one last time with that addition.

**Comment by JordanMartinez** [comment]
Ready to merge.

**Comment by TomasMikula** [comment]
Thanks! Now `InputMap` should have `ifConsumed`, too.

**Pull request merged**
